color_mode: 8
depth_mode: 11
ir_mode: 8
depth_registration: false
depth_time_offset: -0.033
auto_exposure: true
auto_white_balance: true
color_depth_synchronization: false
color_time_offset: -0.033
data_skip: 1
depth_ir_offset_x: 5.0
depth_ir_offset_y: 4.0
depth_registration: false
depth_time_offset: -0.033
ir_time_offset: -0.033
use_device_time: true
z_offset_mm: 0
z_scaling: 1.0